planner_configs:
  RRTkConfigDefault:
    type: geometric::RRT
    range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
    goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
  
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0 #2.5  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
  
  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10  # use k nearest neighbors. default: 10
  
  PersistentPRMstar: # use this with a representative environment to create a roadmap
    type: geometric::PRMstar
    multi_query_planning_enabled: 1
    store_planner_data: 1
    load_planner_data: 1
    planner_data_path: /tmp/roadmap.graph
    range: 2.5
    max_nearest_neighbors: 10

  PersistentPRM: # use this to load a previously created roadmap
    type: geometric::PRM
    multi_query_planning_enabled: 1
    store_planner_data: 0
    load_planner_data: 1
    planner_data_path: /tmp/roadmap.graph
    
  SemiPersistentLazyPRM: # reuses roadmap during lifetime of node but doesn't save/load roadmap to/from disk
    type: geometric::LazyPRM
    multi_query_planning_enabled: 1
    store_planner_data: 0
    load_planner_data: 0
    
  SemiPersistentPRM: # reuses roadmap during lifetime of node but doesn't save/load roadmap to/from disk
    type: geometric::PRM
    #termination_condition: Iteration[1000]
    multi_query_planning_enabled: 1
    store_planner_data: 0
    load_planner_data: 1
    planner_data_path: /tmp/roadmap.graph

ur_manipulator:
  planner_configs:
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - PRMkConfigDefault
    - PersistentPRMstar
    - PersistentPRM
    - SemiPersistentLazyPRM
    - SemiPersistentPRM
  ##Note: commenting the following line lets moveit chose RRTConnect as default planner rather than LBKPIECE
  #projection_evaluator: joints(shoulder_pan_joint,shoulder_lift_joint)
  longest_valid_segment_fraction: 0.005 #rrt connect: 0.0006 funktioniert nicht //ehemals 0.0005
  
