aruco_dictionary_name: "DICT_5X5_250"
aruco_marker_side_length: 0.06
aruco_marker_separation: 0.006
aruco_grid_rows: 4
aruco_grid_cols: 3
camera_calibration_parameters_filename: "src/handeye_calibration_ros2/handeye_realsense/realsense_info.yaml"
image_topic: "/camera/camera/color/image_raw"
aruco_marker_name: "aruco_board"
calculated_camera_optical_frame_name: "camera/color/optical_frame"
marker_data_file_name: "src/handeye_calibration_ros2/handeye_realsense/resource/marker_data_realsense.yaml"
image_filename: "src/handeye_calibration_ros2/handeye_realsense/resource/marker_pose_realsense_{pose_count}.jpg"
robot_data_file_name: "src/handeye_calibration_ros2/handeye_realsense/resource/robot_data_realsense.yaml"
handeye_result_file_name: "src/handeye_calibration_ros2/handeye_realsense/resource/handeye_result_realsense.yaml"
handeye_result_profile_file_name: "src/handeye_calibration_ros2/handeye_realsense/resource/handeye_result_realsense_profile.yaml"

base_link: "link_0"
ee_link: "tool0"
world_frame: "world"
