modbus_client_node:
  ros__parameters:
    modbus_server_host: "192.168.30.20" # IP address of the Modbus server
    modbus_server_port: 502 # Port number of the Modbus server
    modbus_slave_id: 65 # Slave ID of the Modbus server