int32 n                           # number of images
geometry_msgs/Pose[] camera_poses   # n poses (one for each image)
float64[9] intrinsics             # row-major 3x3 K
int32[] screws_per_image          # nx1 array: number of screw detections per image
float64[] screw_u                 # nx1 array: u pixel coordinates for all detections (flattened)
float64[] screw_v                 # nx1 array: v pixel coordinates for all detections (flattened)
int32 max_screws
float64 ransac_inlier_thresh_m
int32 ransac_iters
---
bool success
string message
geometry_msgs/Point[] screw_positions
float64[] screw_fit_rmse_m
geometry_msgs/Pose[] desired_ee_poses