<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>screw_localizer</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="m.e.neuhalfen@t-online.de">remanpilot</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>image_geometry</depend>

  <depend>geometry_msgs</depend>
  <build_depend>screw_interfaces</build_depend>
  <exec_depend>screw_interfaces</exec_depend>

  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>pose_getter</exec_depend>
  <exec_depend>screw_detector</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
