robo_planner:
  ros__parameters:
    # Robot position parameters
    positions:
      # BEMI Position list
      bemi:
        x: [0.3634, 0.1184, 0.0] # X-coordinates of BEMIs 
        y: [0.6815, 0.6178, 0.0] # Y-coordinates of BEMIs 
        z: [0.320, 0.2885, 0.0]  # Z-coordinates of BEMIs 
        RZ_offset: [0.0475, -1.405985086238, 0.0] # Z-rotation offsets of BEMIs 

      # Part Carrier 
      PC:
        # Parts positions inside part carrier 1
        x_1: [-0.351, -0.456, -0.561, -0.666, -0.771, -0.416, -0.589, -0.762]
        y_1: [ 0.341,  0.341,  0.341,  0.341,  0.341,  0.144,  0.144,  0.144] 
        z_1: [ 0.260,  0.260,  0.260,  0.260,  0.260,  0.230,  0.230,  0.230]
        # Bearings positions inside part carrier 2
        x_2: [-0.42013, -0.33364] 
        y_2: [-0.19091, -0.19086]
        z_2: [0.27302, 0.27324] 
        
      # Station positions
      station:
        y_approach: -0.35  # Y-coordinate for approach position
        y_execute: -0.554 #-0.5549700856208801   # Y-coordinate for execution position
        x_positions: [-0.189, -0.0167, 0.1375, 0.27893]  # X-coordinates for different stations

      # Bearing positions inside part placed in BEMI 1 to 3 [BEMI1, BEMI2, BEMI3]
      bearing:
        x: [0.38283, 0.08982]  # X-coordinates for bearing positions
        y: [0.64933, 0.57029]  # Y-coordinates for bearing positions
        z: [0.3389, 0.33903]  # Z-coordinates for bearing positions
  
    # Robot speed parameters 
    speeds:
      ptp: 0.3               # Point-to-Point movement speed
      cartesian_fast: 0.1    # Fast Cartesian movement speed
      cartesian_slow: 0.03   # Slow Cartesian movement speed
    
    # Timing parameters (in milliseconds)
    timings:
      default_wait: 1000     # Default wait time
      gripper_close: 1000    # Time to wait for gripper to close
    

    # TODO not implemented in code yet ############################

    # Deburring process parameters
    deburring:
      circle_radius: 0.023   # Radius of deburring circle
      z_offset: 0.03         # Z-axis offset for deburring
    
    # Safety parameters
    safety:
      placement_offset_z: -0.005 # Z-axis offset for safe placement
    
    # Trajectory parameters
    trajectory:
      circle:
        radius: 0.1          # Radius of circular trajectory
        center: [0.3, 0.3, 0.4]  # Center point of circular trajectory [x, y, z]