robot_planner:
  ros__parameters:
    # Robot position parameters
    positions:
      # BEMI 1 position
      bemi1:
        x: -0.35041  # X-coordinate of BEMI 1
        y: 0.34231   # Y-coordinate of BEMI 1
        z: 0.25      # Z-coordinate of BEMI 1
      
      # BEMI 2 position
      bemi2:
        x: 0.36556   # X-coordinate of BEMI 2
        y: 0.67974   # Y-coordinate of BEMI 2
        z: 0.3107452988624573  # Z-coordinate of BEMI 2
      
      # Station positions
      station:
        y_approach: -0.40759  # Y-coordinate for approach position
        y_execute: -0.55759   # Y-coordinate for execution position
        x_positions: [-0.19138, 0.13816, 0.29433, -0.016]  # X-coordinates for different stations
    
    # Robot speed parameters 
    # TODO not implemented in code yet
    speeds:
      ptp: 0.3               # Point-to-Point movement speed
      cartesian_fast: 0.1    # Fast Cartesian movement speed
      cartesian_slow: 0.03   # Slow Cartesian movement speed
    
    # Timing parameters (in milliseconds)
    timings:
      default_wait: 1000     # Default wait time
      gripper_close: 1000    # Time to wait for gripper to close
    
    # Deburring process parameters
    deburring:
      circle_radius: 0.023   # Radius of deburring circle
      z_offset: 0.03         # Z-axis offset for deburring
    
    # Safety parameters
    safety:
      placement_offset_z: 0.2  # Z-axis offset for safe placement
    
    # Trajectory parameters
    trajectory:
      circle:
        radius: 0.1          # Radius of circular trajectory
        center: [0.3, 0.3, 0.4]  # Center point of circular trajectory [x, y, z]